# Generated by Django 3.2.8 on 2021-10-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20211031_0040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('music_len', models.CharField(max_length=10, verbose_name='Анонс')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'Музыка',
                'verbose_name_plural': 'Музыка',
            },
        ),
    ]
